# Run Terraform Init
init:
	terraform init

# Check Terraform formatting
fmt:
	terraform fmt

# Validate Terraform config
validate:
	terraform validate

# Plan changes
plan:
	terraform plan

# Apply changes automatically
apply:
	terraform apply -auto-approve

# Destroy everything automatically
destroy:
	terraform destroy -auto-approve