standardized_categories = [
    "Accounting", "Actuarial Science", "Administration / Office Management",
    "Advertising / Marketing", "Agricultural Economics", "Agriculture / Agribusiness",
    "Animal Science / Veterinary", "Animation / Game Design", "Anthropology",
    "Archaeology", "Art / Fine Arts", "Artificial Intelligence / Machine Learning",
    "Artificial Intelligence / Robotics Engineering", "Aviation",
    "Automotive / Mechanical Technology", "Banking / Finance",
    "Bioengineering / Biomedical Engineering", "Biochemistry",
    "Biology / Life Sciences", "Biomedical Science", "Biophysics",
    "Biotechnology", "Business Administration / Management",
    "Cartography / Spatial Analysis", "Chemical Engineering", "Chemistry",
    "Child Development / Early Childhood Education", "Civil Engineering",
    "Cognitive Science / Neuroscience", "Communication / Media Studies",
    "Community Development / Social Services", "Computer Engineering",
    "Computer Science / Information Technology", "Construction / Building Management",
    "Counseling / Therapy", "Creative Writing", "Criminal Justice / Law Enforcement",
    "Criminal Psychology", "Cultural Studies / Heritage",
    "Cybersecurity / Information Security", "Data Science / Statistics",
    "Dental / Oral Health", "Design", "Dietetics / Nutrition",
    "Digital Marketing / E-commerce", "Drama / Theatre / Performing Arts",
    "Economics", "Education / Teaching", "Electrical Engineering",
    "Electronic Engineering", "Emergency Management / Public Safety",
    "Energy / Petroleum Engineering", "English / Literature / Linguistics",
    "Environmental Science / Sustainability", "Epidemiology", "Scriptwriting",
    "Fashion / Textile Design", "Film / TV / Media Production",
    "Finance / Investment", "Food Science / Food Technology",
    "Forensic Science / Criminalistics", "Genetics",
    "Gender Studies / Feminist Studies", "Geography / GIS",
    "Geology / Earth Science", "Graphic Design", "Health Administration / Health Management",
    "Healthcare / Medicine", "History / Archaeology",
    "Hospitality Management / Tourism", "Human Resources / Organizational Development",
    "Humanities / Liberal Arts", "Industrial / Organizational Psychology",
    "Industrial Design", "Industrial Engineering / Manufacturing",
    "Information Systems / Data Management", "Interior Design",
    "International Relations / Political Science", "Journalism",
    "Kinesiology / Exercise Science", "Law / Legal Studies",
    "Library and Information Science", "Linguistics",
    "Logistics / Supply Chain Management", "Management Information Systems",
    "Marine / Oceanography", "Materials Science / Nanotechnology",
    "Mathematics / Applied Mathematics", "Mechanical Engineering",
    "Media and Communication", "Medical Laboratory Science",
    "Military Science / Defense Studies", "Ministry / Religious Studies / Theology",
    "Molecular Biology", "Music / Music Technology",
    "Nanotechnology / Materials Science", "Nursing", "Occupational Therapy",
    "Operations Management", "Optometry / Vision Science",
    "Paralegal / Legal Assistance", "Pharmacy / Pharmacology",
    "Philosophy / Ethics", "Physical Therapy / Rehabilitation",
    "Physics / Astronomy", "Political Science / Governance",
    "Product Design", "Psychology", "Public Administration / Public Policy",
    "Public Health", "Publishing", "Real Estate / Property Management",
    "Robotics / Automation Engineering", "Social Work / Human Services",
    "Sociology / Social Sciences", "Software Engineering / Programming",
    "Speech Language Pathology", "Sports Management",
    "Systems Engineering / Technology Management", "Urban Planning",
    "Veterinary Medicine / Animal Care", "Visual Communication"
]

