major_mapping = {
    # Business and Finance Majors
    'accounting': 'Accounting',
    'accountancy': 'Accounting',
    'financial accounting': 'Accounting',
    'auditing': 'Accounting',
    'bcom': 'Accounting',
    'accounts': 'Accounting',
    'commerce': 'Accounting',
    'bookkeeping': 'Accounting',
    'charted accountant': 'Accounting',

    'actuarial science': 'Actuarial Science',
    'actuary': 'Actuarial Science',
    'science acturial': 'Actuarial Science',

    'administration': 'Administration / Office Management',
    'business admin': 'Administration / Office Management',
    'management': 'Administration / Office Management',
    'office management': 'Administration / Office Management',
    'administrative assistant': 'Administration / Office Management',
    'secretarial': 'Administration / Office Management',
    'executive secretary': 'Administration / Office Management',
    'secretary': 'Administration / Office Management',
    'office admiistration': 'Administration / Office Management',

    'finance': 'Banking / Finance',
    'financial': 'Banking / Finance',
    'banking': 'Banking / Finance',
    'corporate finance': 'Banking / Finance',
    'financial servcies': 'Banking / Finance',
    'international finance': 'Banking / Finance',
    'financial analysis': 'Banking / Finance',

    'investment': 'Investment',

    'business': 'Business Administration / Management',
    'business administration': 'Business Administration / Management',
    'business management': 'Business Administration / Management',
    'mba': 'Business Administration / Management',
    'management studies': 'Business Administration / Management',
    'organisational management': 'Business Administration / Management',
    'entrepreneurship': 'Business Administration / Management',
    'commerce management': 'Business Administration / Management',
    'general management': 'Business Administration / Management',

    # Social Science and Humanities Majors
    'anthropology': 'Anthropology',
    'social anthropology': 'Anthropology',
    'cultural anthropology': 'Anthropology',

    'economics': 'Economics',
    'economic consulting': 'Economics',
    'econometry': 'Economics',
    'economical studies': 'Economics',
    'political economy': 'Economics',

    'agricultural economics': 'Agricultural Economics',

    'english': 'Linguistics',
    'german': 'Linguistics',
    'spanish': 'Linguistics',
    'french': 'Linguistics',
    'russian': 'Linguistics',
    'norwegian': 'Linguistics',
    'linguistics': 'Linguistics',
    'applied linguistic': 'Linguistics',
    'hungarian language and literature': 'Linguistics',
    'russian language and literature': 'Linguistics',
    'english language literature': 'Linguistics',
    'language literature': 'Linguistics',

    'philology': 'Philology',
    'literature': 'Philology',

    'writing': 'Creative Writing',
    'art literature': 'Creative Writing',
    'creative writing': 'Creative Writing',

    'scriptwriting': 'Scriptwriting',
    'screenwriting': 'Scriptwriting',
    'playwrighting': 'Scriptwriting',
    'comedic writer': 'Scriptwriting',

    'translation and interpretation': 'Translation / Interpretation Studies',
    'translations': 'Translation / Interpretation Studies',
    'translation': 'Translation / Interpretation Studies',
    'english translation': 'Translation / Interpretation Studies',
    'specialised translation': 'Translation / Interpretation Studies',
    'language translation': 'Translation / Interpretation Studies',
    'translation studies': 'Translation / Interpretation Studies',
    'interpreting for the deaf': 'Translation / Interpretation Studies',

    'history': 'History / Archaeology',
    'archaeology': 'History / Archaeology',
    'history of art': 'History / Archaeology',
    'classics': 'History / Archaeology',
    'american civilization': 'History / Archaeology',

    'liberal arts': 'Humanities / Liberal Arts',
    'humanities': 'Humanities / Liberal Arts',
    'general studies': 'Humanities / Liberal Arts',
    'liberal studies': 'Humanities / Liberal Arts',

    'political science': 'International Relations / Political Science',
    'international relations': 'International Relations / Political Science',
    'diplomacy': 'International Relations / Political Science',
    'foreign service': 'International Relations / Political Science',

    'philosophy': 'Philosophy / Ethics',
    'ethics': 'Philosophy / Ethics',
    'religion / philosophy': 'Philosophy / Ethics',
    'political philosophy': 'Philosophy / Ethics',
    'philosophy and politics': 'Philosophy / Ethics',
    'epistemology': 'Philosophy / Ethics',
    'mental philosophy': 'Philosophy / Ethics',

    'social work': 'Sociology / Social Sciences',
    'sociology': 'Sociology / Social Sciences',
    'social sciences': 'Sociology / Social Sciences',
    'social ecology': 'Sociology / Social Sciences',
    'labor studies': 'Sociology / Social Sciences',
    'social justice': 'Sociology / Social Sciences',
    'social policy': 'Sociology / Social Sciences',

    # Education and Social Service Majors
    'child development': 'Child Development / Early Childhood Education',
    'early childhood education': 'Child Development / Early Childhood Education',
    'child care': 'Child Development / Early Childhood Education',
    'child life specialist': 'Child Development / Early Childhood Education',
    'family studies': 'Child Development / Early Childhood Education',
    'child and family studies': 'Child Development / Early Childhood Education',

    'community development': 'Community Development / Social Services',
    'social services': 'Community Development / Social Services',
    'human services': 'Community Development / Social Services',
    'community studies': 'Community Development / Social Services',
    'community support worker': 'Community Development / Social Services',

    'counselling': 'Counseling / Therapy',
    'counseling psychology': 'Counseling / Therapy',
    'mental health': 'Counseling / Therapy',
    'clinical mental health counseling': 'Counseling / Therapy',
    'educational counseling': 'Counseling / Therapy',
    'rehabilitation counseling': 'Counseling / Therapy',
    'school counseling': 'Counseling / Therapy',

    'education': 'Education / Teaching',
    'elementary education': 'Education / Teaching',
    'secondary education': 'Education / Teaching',
    'teaching': 'Education / Teaching',
    'pedagogy': 'Education / Teaching',
    'educational leadership': 'Education / Teaching',
    'special education': 'Education / Teaching',
    'education technology': 'Education / Teaching',
    'human development': 'Education / Teaching',
    'pedagogics': 'Education / Teaching',
    'special ed': 'Education / Teaching',

    'clinical social work': 'Social Work / Human Services',
    'social welfare': 'Social Work / Human Services',
    'case worker': 'Social Work / Human Services',

    # Government, Law, and Public Service Majors
    'criminology': 'Criminal Justice / Law Enforcement',
    'law enforcement': 'Criminal Justice / Law Enforcement',
    'criminalistics': 'Criminal Justice / Law Enforcement',
    'fbi': 'Criminal Justice / Law Enforcement',
    'police': 'Criminal Justice / Law Enforcement',

    'emergency medical services': 'Emergency Management / Public Safety',
    'emergency management': 'Emergency Management / Public Safety',
    'homeland security': 'Emergency Management / Public Safety',
    'fire science': 'Emergency Management / Public Safety',
    'public safety': 'Emergency Management / Public Safety',
    'safety engineering': 'Emergency Management / Public Safety',

    'law': 'Law / Legal Studies',
    'law degree': 'Law / Legal Studies',
    'legal studies': 'Law / Legal Studies',
    'criminal law': 'Law / Legal Studies',
    'jurisprudence': 'Law / Legal Studies',
    'law and justice': 'Law / Legal Studies',

    'paralegal': 'Paralegal / Legal Assistance',
    'legal assistant': 'Paralegal / Legal Assistance',
    'paralegal studies': 'Paralegal / Legal Assistance',
    'legal assistance': 'Paralegal / Legal Assistance',

    'government': 'Political Science / Governance',
    'public governance': 'Political Science / Governance',
    'international politics': 'Political Science / Governance',

    'public administration': 'Public Administration / Public Policy',
    'public policy': 'Public Administration / Public Policy',
    'public service': 'Public Administration / Public Policy',

    'public health': 'Public Health',
    'health promotion': 'Public Health',
    'community health': 'Public Health',
    'environmental health': 'Public Health',
    'public health administration': 'Public Health',
    'occupational health': 'Public Health',

    'epidemiology': 'Epidemiology',

    # Arts, Media, and Design Majors
    'art': 'Art / Fine Arts',
    'fine arts': 'Art / Fine Arts',
    'studio art': 'Art / Fine Arts',
    'visual arts': 'Art / Fine Arts',
    'painting': 'Art / Fine Arts',
    'drawing': 'Art / Fine Arts',
    'art history': 'Art / Fine Arts',
    'art therapy': 'Art / Fine Arts',

    'design': 'Design',
    'photograrpy': 'Design',
    'visual art': 'Design',
    'graphic design': 'Graphic Design',
    'industrial design': 'Industrial Design',
    'product design': 'Product Design',
    'visual communication': 'Design',
    'interior design': 'Interior Design',

    'animation': 'Animation / Game Design',
    'simulation animation and gaming': 'Animation / Game Design',
    'game developer': 'Animation / Game Design',

    'drama': 'Drama / Theatre / Performing Arts',
    'theatre': 'Drama / Theatre / Performing Arts',
    'performing arts': 'Drama / Theatre / Performing Arts',
    'acting': 'Drama / Theatre / Performing Arts',
    'musical theatre': 'Drama / Theatre / Performing Arts',
    'theatrics': 'Drama / Theatre / Performing Arts',
    'theatrical arts': 'Drama / Theatre / Performing Arts',

    'film': 'Film / TV / Media Production',
    'tv film': 'Film / TV / Media Production',
    'media production': 'Film / TV / Media Production',
    'audiovisual': 'Film / TV / Media Production',
    'cinematography': 'Film / TV / Media Production',
    'animation': 'Film / TV / Media Production',
    'film and television': 'Film / TV / Media Production',

    'journalism': 'Journalism',
    'publishing': 'Publishing',
    'broadcast journalism': 'Journalism',

    'gender studies': 'Gender Studies / Feminist Studies',
    'history and women studies': 'Gender Studies / Feminist Studies',
    'women gender studies': 'Gender Studies / Feminist Studies',

    'technical communication': 'Media and Communication',
    'communication': 'Media and Communication',
    'mass communication': 'Media and Communication',
    'media studies': 'Media and Communication',
    'corporate communication': 'Media and Communication',
    'communications media': 'Media and Communication',
    'telecommunications': 'Media and Communication',
    'communication studies': 'Media and Communication',
    'multimedia arts': 'Media and Communication',
    'mass comm': 'Media and Communication',
    'masscom': 'Media and Communication',
    'media culture': 'Media and Communication',

    'music': 'Music / Music Technology',
    'music technology': 'Music / Music Technology',
    'sound engineering': 'Music / Music Technology',
    'music education': 'Music / Music Technology',
    'vocal performance': 'Music / Music Technology',
    'piano performance': 'Music / Music Technology',
    'music production': 'Music / Music Technology',
    'music therapy': 'Music / Music Technology',

    # Engineering and Technology Majors
    'aerospace engineering': 'Aerospace Engineering',
    'astronautics': 'Aerospace Engineering',
    'aircraft maintenance': 'Aerospace Engineering',
    'aerospace': 'Aerospace Engineering',

    'aeronautical engineering': 'Aviation',
    'aeronautical engr.': 'Aviation',
    'aviation management': 'Aviation',
    'pilot training': 'Aviation',

    'automotive': 'Automotive / Mechanical Technology',
    'diesel mechanic': 'Automotive / Mechanical Technology',
    'automotive technology': 'Automotive / Mechanical Technology',
    'mechatronics': 'Automotive / Mechanical Technology',

    'bioengineering': 'Bioengineering / Biomedical Engineering',
    'biomedical engineering': 'Bioengineering / Biomedical Engineering',
    'biological engineering': 'Bioengineering / Biomedical Engineering',
    'biosystems engineering': 'Bioengineering / Biomedical Engineering',
    'biomechanical engineering': 'Bioengineering / Biomedical Engineering',

    'chemical engineering': 'Chemical Engineering',
    'chemical technology': 'Chemical Engineering',
    'chemical process engineering': 'Chemical Engineering',

    'civil engineering': 'Civil Engineering',
    'civil engineering': 'Civil Engineering',
    'civil engineering': 'Civil Engineering',
    'construction engineering': 'Civil Engineering',
    'architectural engineering': 'Civil Engineering',
    'structural engineering': 'Civil Engineering',
    'geotechnical engineering': 'Civil Engineering',

    'computer engineering': 'Computer Engineering',
    'electrical and computer engineering': 'Computer Engineering',
    'computer system engineering': 'Computer Engineering',
    'computer systems': 'Computer Engineering',

    'computer science': 'Computer Science / Information Technology',
    'information technology': 'Computer Science / Information Technology',
    'it': 'Computer Science / Information Technology',
    'computing': 'Software Engineering / Programming',
    'software engineering': 'Software Engineering / Programming',
    'programming': 'Software Engineering / Programming',
    'software development': 'Software Engineering / Programming',
    'computer programming': 'Software Engineering / Programming',
    'computing science': 'Software Engineering / Programming',
    'it specialist': 'Software Engineering / Programming',
    'applied informatics': 'Software Engineering / Programming',

    'electrical engineering': 'Electrical Engineering',
    'electircal engineering': 'Electrical Engineering',
    'electrical electronic engineering': 'Electrical Engineering',
    'electronics': 'Electrical Engineering',
    'power engineering': 'Electrical Engineering',
    'heating power': 'Electrical Engineering',

    'electronic engineering': 'Electronic Engineering',
    'electronics communication engineering': 'Electronic Engineering',
    'electronic systems engineering': 'Electronic Engineering',

    'energy': 'Energy / Petroleum Engineering',
    'petroleum engineering': 'Energy / Petroleum Engineering',
    'nuclear engineering': 'Energy / Petroleum Engineering',
    'oil and gas': 'Energy / Petroleum Engineering',
    'renewable engery': 'Energy / Petroleum Engineering',

    'industrial engineering': 'Industrial Engineering / Manufacturing',
    'manufacturing': 'Industrial Engineering / Manufacturing',
    'production': 'Industrial Engineering / Manufacturing',
    'quality engineering': 'Industrial Engineering / Manufacturing',
    'industrial distribution': 'Industrial Engineering / Manufacturing',
    'manufacturing engineering': 'Industrial Engineering / Manufacturing',

    'mechanical engineering': 'Mechanical Engineering',
    'mechnical engineering': 'Mechanical Engineering',
    'automotive engineering': 'Mechanical Engineering',
    'electromechanical': 'Mechanical Engineering',
    'naval engineering': 'Mechanical Engineering',

    'systems engineering': 'Systems Engineering / Technology Management',
    'technology management': 'Systems Engineering / Technology Management',
    'computer information systems': 'Systems Engineering / Technology Management',
    'business information systems': 'Systems Engineering / Technology Management',

    'robotics': 'Robotics / Automation Engineering',
    'cybersecurity': 'Cybersecurity / Information Security',
    'artificial intelligence': 'Artificial Intelligence / Machine Learning',
    'ai engineering': 'Artificial Intelligence / Robotics Engineering',

    # Science and Math Majors
    'agriculture': 'Agriculture / Agribusiness',
    'agribusiness': 'Agriculture / Agribusiness',
    'horticulture': 'Agriculture / Agribusiness',
    'agronomy': 'Agriculture / Agribusiness',
    'agricultural economics': 'Agriculture / Agribusiness',

    'animal science': 'Animal Science / Veterinary',
    'veterinary': 'Animal Science / Veterinary',
    'animal care': 'Animal Science / Veterinary',
    'animal behavior': 'Animal Science / Veterinary',
    'equine': 'Animal Science / Veterinary',
    'zoologist': 'Animal Science / Veterinary',
    'veterinary nursing': 'Animal Science / Veterinary',
    'animal study': 'Animal Science / Veterinary',

    'biochemistry': 'Biochemistry',
    'molecular biology': 'Biochemistry',
    'bio-chemistry': 'Biochemistry',
    'chem biochem': 'Biochemistry',

    'biology': 'Biology / Life Sciences',
    'biological sciences': 'Biology / Life Sciences',
    'life sciences': 'Biology / Life Sciences',
    'natural sciences': 'Biology / Life Sciences',

    'genetics': 'Genetics',
    'genetic engineering': 'Genetics',

    'molecular biology': 'Molecular Biology',

    'microbiology': 'Microbiology',
    'medical microbiology': 'Microbiology',

    'biophysics': 'Biophysics',
    'medical biophysics': 'Biophysics',

    'neuroscience': 'Neuroscience / Cognitive Science',
    'cognitive neuroscience': 'Neuroscience / Cognitive Science',
    'cognitive science': 'Neuroscience / Cognitive Science',

    'biotechnology': 'Biotechnology',
    'biomedical technology': 'Biotechnology',
    'biotecnology': 'Biotechnology',
    'biotechnology engineering': 'Biotechnology',

    'chemistry': 'Chemistry',
    'analytical chemistry': 'Chemistry',
    'forensic chemistry': 'Chemistry',
    'applied chemistry': 'Chemistry',
    'industrial chemistry': 'Chemistry',

    'data science': 'Data Science / Statistics',
    'statistics': 'Data Science / Statistics',
    'applied statistics': 'Data Science / Statistics',
    'econometrics and statistics': 'Data Science / Statistics',
    'mathematical statistics': 'Data Science / Statistics',
    'data analytics': 'Data Science / Statistics',

    'environmental science': 'Environmental Science / Sustainability',
    'environmental studies': 'Environmental Science / Sustainability',
    'sustainability': 'Environmental Science / Sustainability',
    'environmental health': 'Environmental Science / Sustainability',
    'ecology': 'Environmental Science / Sustainability',
    'marine environmental science': 'Environmental Science / Sustainability',
    'sustainability': 'Environmental Science / Sustainability',
    'environmental management': 'Environmental Science / Sustainability',
    'environmental managment': 'Environmental Science / Sustainability',
    'environmental policy': 'Environmental Science / Sustainability',
    'wildlife management': 'Environmental Science / Sustainability',
    'biodiversity': 'Environmental Science / Sustainability',

    'forensic science': 'Forensic Science / Criminalistics',
    'forensic pathology': 'Forensic Science / Criminalistics',
    'cyber forensics': 'Forensic Science / Criminalistics',
    'investigative forensics': 'Forensic Science / Criminalistics',

    'geography': 'Geography / GIS',
    'geographygis': 'Geography / GIS',
    'gis': 'Geography / GIS',
    'ge': 'Geography / GIS',
    'geomatics': 'Geography / GIS',
    'cultural geography': 'Geography / GIS',
    'remote sensing': 'Geography / GIS',
    'geospatial science': 'Geography / GIS',

    'cartography': 'Cartography / Spatial Analysis',

    'geology': 'Geology / Earth Science',
    'earth science': 'Geology / Earth Science',
    'geoscience': 'Geology / Earth Science',
    'geophysics': 'Geology / Earth Science',
    'archaeology': 'Geology / Earth Science',
    'mining engineering': 'Geology / Earth Science',
    'geologists': 'Geology / Earth Science',

    'marine': 'Marine / Oceanography',
    'oceanography': 'Marine / Oceanography',
    'marine biology': 'Marine / Oceanography',
    'coastal conservation': 'Marine / Oceanography',
    'marine biology': 'Marine / Oceanography',
    'marine bio': 'Marine / Oceanography',
    'marine science': 'Marine / Oceanography',
    'marine engineering': 'Marine / Oceanography',

    'materials science': 'Materials Science / Nanotechnology',
    'nanotechnology': 'Materials Science / Nanotechnology',
    'polymer engineering': 'Materials Science / Nanotechnology',
    'metallurgy': 'Materials Science / Nanotechnology',
    'metallurgical engineering': 'Materials Science / Nanotechnology',

    'math': 'Mathematics / Applied Mathematics',
    'mathematics': 'Mathematics / Applied Mathematics',
    'applied mathematics': 'Mathematics / Applied Mathematics',
    'theoretical mathematics': 'Mathematics / Applied Mathematics',
    'mathematical engineering': 'Mathematics / Applied Mathematics',

    'physics': 'Physics / Astronomy',
    'astronomy': 'Physics / Astronomy',
    'astrophysics': 'Physics / Astronomy',
    'applied physics': 'Physics / Astronomy',
    'physical science': 'Physics / Astronomy',

    # Health and Medical Majors
    'dental': 'Dental / Oral Health',
    'dental assisting': 'Dental / Oral Health',
    'dental hygiene': 'Dental / Oral Health',
    'dentistry': 'Dental / Oral Health',
    'dental hygenistry': 'Dental / Oral Health',
    'dentist': 'Dental / Oral Health',

    'nutrition': 'Dietetics / Nutrition',
    'dietetics': 'Dietetics / Nutrition',
    'food science and nutrition': 'Dietetics / Nutrition',
    'human nutrition': 'Dietetics / Nutrition',
    'nutritional sciences': 'Dietetics / Nutrition',
    'nutrition science': 'Dietetics / Nutrition',

    'health administration': 'Health Administration / Health Management',
    'healthcare management': 'Health Administration / Health Management',
    'health services management': 'Health Administration / Health Management',
    'elder care administration': 'Health Administration / Health Management',
    'hospital administration': 'Health Administration / Health Management',

    'healthcare': 'Healthcare / Medicine',
    'medicine': 'Healthcare / Medicine',
    'doctor': 'Healthcare / Medicine',
    'pre med': 'Healthcare / Medicine',
    'medical': 'Healthcare / Medicine',
    'physician': 'Healthcare / Medicine',
    'herbal medicine': 'Healthcare / Medicine',

    'biomedical science': 'Biomedical Science',
    'gerontology': 'Biomedical Science',

    'kinesiology': 'Kinesiology / Exercise Science',
    'exercise science': 'Kinesiology / Exercise Science',
    'sports science': 'Kinesiology / Exercise Science',
    'health exercise science': 'Kinesiology / Exercise Science',
    'human kinetics': 'Kinesiology / Exercise Science',
    'exercise physiology': 'Kinesiology / Exercise Science',
    'sport and exercise science': 'Kinesiology / Exercise Science',

    'sports management': 'Sports Management',
    'sports medicine': 'Sports Management',

    'medical laboratory science': 'Medical Laboratory Science',
    'clinical laboratory science': 'Medical Laboratory Science',
    'medical technology': 'Medical Laboratory Science',
    'lab tech': 'Medical Laboratory Science',
    'health informatics': 'Medical Laboratory Science',

    'nursing': 'Nursing',
    'pre nursing': 'Nursing',
    'prenursing': 'Nursing',
    'rn': 'Nursing',
    'nurse': 'Nursing',
    'practical nursing': 'Nursing',

    'psychology': 'Psychology',
    'psych': 'Psychology',
    'psychology and education': 'Psychology',
    'criminal psychology': 'Criminal Psychology',
    'clinical psychology': 'Clinical Psychology',
    'counseling psychology': 'Counseling Psychology / Therapy',
    'industrial psychology': 'Industrial / Organizational Psychology',

    'occupational therapy': 'Occupational Therapy',
    'occupational therapy assistant': 'Occupational Therapy',
    'certified occupational therapy assistant': 'Occupational Therapy',
    'pre occupational therapy': 'Occupational Therapy',

    'optometry': 'Optometry / Vision Science',
    'vision science': 'Optometry / Vision Science',
    'pre optometry': 'Optometry / Vision Science',
    'ophthalmic technician': 'Optometry / Vision Science',
    'optician': 'Optometry / Vision Science',

    'pharmacy': 'Pharmacy / Pharmacology',
    'pharmaceutical': 'Pharmacy / Pharmacology',
    'pharmacology': 'Pharmacy / Pharmacology',
    'pharmacist': 'Pharmacy / Pharmacology',
    'pre pharmacy': 'Pharmacy / Pharmacology',

    'physical therapy': 'Physical Therapy / Rehabilitation',
    'physical therapist assistant': 'Physical Therapy / Rehabilitation',
    'rehabilitation': 'Physical Therapy / Rehabilitation',
    'physiotherapy': 'Physical Therapy / Rehabilitation',
    'therapeutic recreation': 'Physical Therapy / Rehabilitation',

    'speech language pathology': 'Speech Language Pathology',
    'communication sciences disorders': 'Speech Language Pathology',
    'audiology speech pathology': 'Speech Language Pathology',
    'speech therapy': 'Speech Language Pathology',
    'speech pathologiy': 'Speech Language Pathology',

    # Culinary, Hospitality, and Logistics Majors
    'construction': 'Construction / Building Management',
    'construction management': 'Construction / Building Management',
    'building management': 'Construction / Building Management',
    'civil construction': 'Construction / Building Management',
    'building surveying': 'Construction / Building Management',

    'urban planning': 'Urban Planning',
    'urban studies': 'Urban Planning',

    'culinary': 'Culinary',
    'pastry': 'Culinary',
    'cook': 'Culinary',
    'food service management': 'Culinary',
    'gastronomy': 'Culinary',
    'culinary management': 'Culinary',

    'food science': 'Food Science / Food Technology',
    'food technology': 'Food Science / Food Technology',
    'food nutrition': 'Food Science / Food Technology',
    'culinary science': 'Food Science / Food Technology',
    'meat science': 'Food Science / Food Technology',

    'hospitality': 'Hospitality Management / Tourism',
    'hotel management': 'Hospitality Management / Tourism',
    'hospitality management': 'Hospitality Management / Tourism',
    'tourism': 'Hospitality Management / Tourism',
    'international tourism': 'Hospitality Management / Tourism',
    'events management': 'Hospitality Management / Tourism',
    'event management': 'Hospitality Management / Tourism',
    'hospitality and tourism': 'Hospitality Management / Tourism',

    'logistics': 'Logistics / Supply Chain Management',
    'supply chain management': 'Logistics / Supply Chain Management',
    'global supply chain': 'Logistics / Supply Chain Management',
    'transportation management': 'Logistics / Supply Chain Management',
    'international shipping': 'Logistics / Supply Chain Management',
    'transport': 'Logistics / Supply Chain Management',

    'operations management': 'Operations Management',
    'quality management': 'Operations Management',
    'production management': 'Operations Management',
    'business operations': 'Operations Management',
    'management operations': 'Operations Management',
    'project management': 'Operations Management',

    'real estate': 'Real Estate / Property Management',
    'property management': 'Real Estate / Property Management',
    'land administration': 'Real Estate / Property Management',
    'land surveying': 'Real Estate / Property Management',
    'valuation': 'Real Estate / Property Management',
    'real estate management': 'Real Estate / Property Management',

    'digital marketing': 'Digital Marketing / E-commerce',
    'marketing': 'Digital Marketing / E-commerce',
    'international marketing': 'Digital Marketing / E-commerce',
    'marketing analytics': 'Digital Marketing / E-commerce',
    'marketing communications': 'Digital Marketing / E-commerce',
    'marketing management': 'Digital Marketing / E-commerce',
    'business marketing': 'Digital Marketing / E-commerce',
    'sports marketing': 'Digital Marketing / E-commerce',

    # Other Specialized Fields
    'fashion': 'Fashion / Textile Design',
    'fashion design': 'Fashion / Textile Design',
    'textile design': 'Fashion / Textile Design',
    'fashion merchandising': 'Fashion / Textile Design',
    'apparel design': 'Fashion / Textile Design',
    'clothing technology': 'Fashion / Textile Design',
    'cosmetoly': 'Fashion / Textile Design',
    'cosmetology': 'Fashion / Textile Design',
    'style': 'Fashion / Textile Design',
    'fashion business': 'Fashion / Textile Design',
    'fashion apparel': 'Fashion / Textile Design',
    'fashion merchandise': 'Fashion / Textile Design',

    'library and information science': 'Library and Information Science',
    'library management': 'Library and Information Science',
    'information science': 'Library and Information Science',
    'library tech': 'Library and Information Science',
    'library science': 'Library and Information Science',
    'bookkeeper': 'Library and Information Science',

    'ministry': 'Ministry / Religious Studies / Theology',
    'religious studies': 'Ministry / Religious Studies / Theology',
    'theology': 'Ministry / Religious Studies / Theology',
    'biblical studies': 'Ministry / Religious Studies / Theology',
    'christian ministries': 'Ministry / Religious Studies / Theology',
    'religious education': 'Ministry / Religious Studies / Theology',
    'biblical and theological studies': 'Ministry / Religious Studies / Theology',

    'military': 'Military Science / Defense Studies',
    'military science': 'Military Science / Defense Studies',
    'military sciences': 'Military Science / Defense Studies',
    'military psychology': 'Military Science / Defense Studies',

    'cultural studies': 'Cultural Studies / Heritage',
    'museum studies': 'Cultural Studies / Heritage',
    'intercultural studies': 'Cultural Studies / Heritage'
}

